require "raylib"

-- Initialization
--------------------------------------------------------------------------------------
local SCREEN_WIDTH: uint16 <comptime> = 800
local SCREEN_HEIGHT: uint16 <comptime> = 450

rl.setConfigFlags(rl.configFlags.VSYNC_HINT) -- Enable VSYNC
rl.initWindow(SCREEN_WIDTH,SCREEN_HEIGHT, "raylib-nelua [core] example - basic window")

--------------------------------------------------------------------------------------

-- Main game loop

while not rl.windowShouldClose() do        -- Detect window close button or ESC key
  -- Update
  ----------------------------------------------------------------------------------
  -- TODO: Update your variables here
  ----------------------------------------------------------------------------------

  -- Draw
  ----------------------------------------------------------------------------------
  
  rl.beginDrawing()

    rl.clearBackground(rl.RAYWHITE)

    rl.drawText("Congrats! You created your first window!", 190, 200, 20, rl.LIGHTGRAY)

  rl.endDrawing()
  -----------------------------------------------------------------------------------
end

-- De-Initialization
-------------------------------------------------------------------------------------
rl.closeWindow()       -- Close window and OpenGL context
-------------------------------------------------------------------------------------